import java .util.Scanner;
class practiceDay05 {
    public static void main(String[] args) {
    //00PS CLASS : a class that contains only one method which is the main method
    oops stands for object oriented programming system. it is a programming paradigm that uses objects and classes to    design and develop software. it provides a way to structure code in a more modular and reusable way, making it easier to maintain and scale.
    //syntax: class class_name{
    class oops
    {
        //class body
    }
    

}       